package com.zup.nimbus.core.operations

val defaultOperations = mutableMapOf(
  "and" to and,
  "capitalize" to capitalize,
  "concat" to concat,
  "condition" to condition,
  "contains" to contains,
  "divide" to divide,
  "eq" to eq,
  "gt" to gt,
  "gte" to gte,
  "insert" to insert,
  "isEmpty" to isEmpty,
  "isNull" to isNull,
  "length" to length,
  "lowercase" to lowercase,
  "lt" to lt,
  "lte" to lte,
  "match" to match,
  "multiply" to multiply,
  "not" to not,
  "or" to or,
  "remove" to remove,
  "removeIndex" to removeIndex,
  "replace" to replace,
  "substr" to substr,
  "subtract" to subtract,
  "sum" to sum,
  "union" to union,
  "uppercase" to uppercase,
)
